# Generated by Django 5.0.6 on 2024-06-29 07:54

import assignment1app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('uploaded_time', models.DateTimeField(validators=[assignment1app.models.validate_not_past])),
                ('audio_file', models.FileField(upload_to='audio_files/')),
            ],
        ),
    ]
